version: '2'
services:
    luulpos-app:
        image: luulpos
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://luulpos-mysql:3306/luulpos?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://luulpos-elasticsearch:9200
        ports:
            - 8080:8080
    luulpos-mysql:
        extends:
            file: mysql.yml
            service: luulpos-mysql
    luulpos-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: luulpos-elasticsearch
